version: '3.8'

services:
  app:    
    build:
      context: .
    volumes:
      - .:/code      
    ports:
      - "5050:5050"
    environment:
      - DB_URL=mongodb://edelacruz:sip18DNK.*@10.89.2.2:27017
      - SECRET_KEY=bgvfcdxs654321
    depends_on:
      - mongodb

  mongodb:    
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=edelacruz
      - MONGO_INITDB_ROOT_PASSWORD=sip18DNK.* 
    volumes:
      - data:/data/db


volumes:
  data:
    
